### ISSUE TITLE
关于linux上的git

### ISSUE THREAD

**Issue by Mu-lnz** [QuentinHsu/Document#1]
github在linux(ubutnu)上命令几乎完全，不过windows有个桌面端(GitHub Desktop,对于不想学git命令的是真的好用).[手动滑稽]

**Comment by QuentinHsu** [comment]
> github在linux(ubutnu)上命令几乎完全，不过windows有个桌面端(GitHub Desktop,对于不想学git命令的是真的好用).[手动滑稽]

感觉你可能对 GitHub 、Git 有概念上的误解。GitHub 并没有所谓的命令。Git 才有命令。

另外对于程序员新手在学习用 Git 进行版本控制时，入门不建议使用图形化工具。对于一切新的命令（自己未使用过的）都建议通过命令行来学会使用，熟练了才能知道图形化工具”封装“的命令到底是在干啥。（另外吐槽一句，有些图形化工具，自带汉化，然后就把封装的命令取了个不太能看懂意思的中文名……只能先 test，才敢用……
